spring:
  application:
    name: BookingCreelHouse
  datasource:
    url: jdbc:h2:file:./booking.db
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  # Step 1a: Configure SSL with the certificate and private key
  ssl:
    bundle:
      pem:
        web:
          keystore:
            private-key: "base64:LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JR0hBZ0VBTUJNR0J5cUdTTTQ5QWdFR0NDcUdTTTQ5QXdFSEJHMHdhd0lCQVFRZ2x5K0Fvd1duY0l6RUlnUDIKTVVaNjdmdzBaRFZjUEJmVEJXdk9tR0dTWXZLaFJBTkNBQVRwbEwyTEZTcEtLS3dvNCtDdFE3UmNFMnRlU1ZNawpDdCtsK2FtbTh0VDJnL2JjTXRybUNVeXdaNFR3cVBtTU9tcnpqSDlJSDh3WFpCdlcrbFRLTDkzLwotLS0tLUVORCBQUklWQVRFIEtFWS0tLS0tCg=="   # résultat de localhost-key.pem
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNXRENDQWYrZ0F3SUJBZ0lSQUlDNHpEMG4vcVlHbTQyVktPOG82OEF3Q2dZSUtvWkl6ajBFQXdJd2daVXgKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURTFNRE1HQTFVRUN3d3NlVzkxYzNKaAphRUI1YjNWemNtRm9MVlJvYVc1clVHRmtMVVV4TkMxSFpXNHROU0FvV1c5MWMzSmhhQ2t4UERBNkJnTlZCQU1NCk0yMXJZMlZ5ZENCNWIzVnpjbUZvUUhsdmRYTnlZV2d0VkdocGJtdFFZV1F0UlRFMExVZGxiaTAxSUNoWmIzVnoKY21Gb0tUQWVGdzB5TmpBME1UVXdOelF3TXpoYUZ3MHlPREEzTVRVd056UXdNemhhTUdBeEp6QWxCZ05WQkFvVApIbTFyWTJWeWRDQmtaWFpsYkc5d2JXVnVkQ0JqWlhKMGFXWnBZMkYwWlRFMU1ETUdBMVVFQ3d3c2VXOTFjM0poCmFFQjViM1Z6Y21Gb0xWUm9hVzVyVUdGa0xVVXhOQzFIWlc0dE5TQW9XVzkxYzNKaGFDa3dXVEFUQmdjcWhrak8KUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVRwbEwyTEZTcEtLS3dvNCtDdFE3UmNFMnRlU1ZNa0N0K2wrYW1tOHRUMgpnL2JjTXRybUNVeXdaNFR3cVBtTU9tcnpqSDlJSDh3WFpCdlcrbFRLTDkzL28yUXdZakFPQmdOVkhROEJBZjhFCkJBTUNCYUF3RXdZRFZSMGxCQXd3Q2dZSUt3WUJCUVVIQXdFd0h3WURWUjBqQkJnd0ZvQVVuMjJYZFdYNnZ0T1AKdkgzMUd6M2VaaDR0c1c4d0dnWURWUjBSQkJNd0VZSVBiRzlqWVd3dU1IaGtZbVV1WkdWMk1Bb0dDQ3FHU000OQpCQU1DQTBjQU1FUUNJQWtRb1ZOTFVjYTFGSmdCcnVwcjYxVGhVbUI4QndadEhhVjJ1OVJqKzlTM0FpQnBzOGNDCllrT2hHWEVnZDE4Sm1oWHd3bU9vMXIzVUE0VGF4b2tCdmZyQmR3PT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo="    # résultat de localhost-cert.pem
          truststore:
            certificate: "base64:LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNiekNDQWhhZ0F3SUJBZ0lSQU1rZE00MFhIMDFEbVZmVStJRStBTlV3Q2dZSUtvWkl6ajBFQXdJd2daVXgKSGpBY0JnTlZCQW9URlcxclkyVnlkQ0JrWlhabGJHOXdiV1Z1ZENCRFFURTFNRE1HQTFVRUN3d3NlVzkxYzNKaAphRUI1YjNWemNtRm9MVlJvYVc1clVHRmtMVVV4TkMxSFpXNHROU0FvV1c5MWMzSmhhQ2t4UERBNkJnTlZCQU1NCk0yMXJZMlZ5ZENCNWIzVnpjbUZvUUhsdmRYTnlZV2d0VkdocGJtdFFZV1F0UlRFMExVZGxiaTAxSUNoWmIzVnoKY21Gb0tUQWVGdzB5TmpBME1UVXdOek01TkRKYUZ3MHpOakEwTVRVd056TTVOREphTUlHVk1SNHdIQVlEVlFRSwpFeFZ0YTJObGNuUWdaR1YyWld4dmNHMWxiblFnUTBFeE5UQXpCZ05WQkFzTUxIbHZkWE55WVdoQWVXOTFjM0poCmFDMVVhR2x1YTFCaFpDMUZNVFF0UjJWdUxUVWdLRmx2ZFhOeVlXZ3BNVHd3T2dZRFZRUURERE50YTJObGNuUWcKZVc5MWMzSmhhRUI1YjNWemNtRm9MVlJvYVc1clVHRmtMVVV4TkMxSFpXNHROU0FvV1c5MWMzSmhhQ2t3V1RBVApCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFRTS9OUlBsazBYanpNeHlKUFF3cUpKdEp4dFBEMmYrdDQ1CmJxU01ZU3A0aFhyTW5LZUQzZWFXZVFxc04yNWE3ajlaT2pYN2VrbzFORS8xMTJreDA1Z21vMFV3UXpBT0JnTlYKSFE4QkFmOEVCQU1DQWdRd0VnWURWUjBUQVFIL0JBZ3dCZ0VCL3dJQkFEQWRCZ05WSFE0RUZnUVVuMjJYZFdYNgp2dE9QdkgzMUd6M2VaaDR0c1c4d0NnWUlLb1pJemowRUF3SURSd0F3UkFJZ09yR2FOMzVrL2EvRmdjcWNGVzJFCnlGMWtDYjU5cXJQYzU5a3p3cGNKNXdVQ0lIZ1lmYWZRQURSajh2L3hMTkZETmliUS9xNlVNVFJQd256Rm5CU3cKZ0ZTdAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="    # résultat de rootCA.pem
  # Step 1a: End of SSL configuration

server:
  port: 8443
  # Step 1b: Enable SSL and specify ssl bundle
  ssl:
    bundle: "web"
  # Step 1b: End of SSL configuration
  # Step 5: Configure session cookie with SameSite attribute
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict
  # Step 5: End of session cookie configuration